version: '3'
services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
      network: host # just for testing
    ports:
      - "8080:8080"
    networks:
      - traefik
    depends_on:
      - redis
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.frontend.rule=Host:loadingif.io"
    #   - "traefik.port=8080"
  redis:
    hostname: redis
    image: redis:alpine
    # volumes:
    #   - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - traefik
  # traefik:
  #   image: traefik:v2.2
  #   ports:
  #     - "80:80"
  #     - "443:443"
  # #   volumes:
  # #     - /var/run/docker.sock:/var/run/docker.sock
  # #     - ./traefik.toml:/traefik.toml
  #   networks:
  #     - traefik

networks:
  traefik:
    external: true
# volumes:
#   redis-data:
